<?php
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function fibonacci($first, $second, $max_limit, $FibonacciNumbers){

	if($first > 0 && $second > 0 && $max_limit > 0 ){
		
		$sum = $first + $second;
		if( $sum <= $max_limit){
			$FibonacciNumbers[] = $sum;
			return fibonacci($second, $sum, $max_limit, $FibonacciNumbers);
		}
		return $FibonacciNumbers;
	}
	return 0;
}
function sumOfEvenFibonacciNumbers($FibonacciArrayList){
		
	if(is_array($FibonacciArrayList)){
		$sum = 0;
		foreach($FibonacciArrayList as $num){
			if($num%2 == 0){
				$sum = $sum + $num;
			}
		}
		return $sum;
	}
	return 0;
}
$FibonacciNumbers[] = 1;
$FibonacciNumbers[] = 2;
$res = fibonacci($first='1', $second='2', $max_limit='4000000', $FibonacciNumbers);
print_r($res);
echo sumOfEvenFibonacciNumbers($res);
?>